### ISSUE TITLE
get_survey() error

### ISSUE THREAD

**Issue by mle2718** [lkerr/groundfish-MSE#212]
When I try to run an Economic model using ``runSim.R``, I get this error:

```
Error in get_survey(F_full = 0, M = 0, N = J1N[y, ], slxC[y, ], slxI = selI,  : 
  argument "DecCatch" is missing, with no default
```
That comes from this portion of code:
```
            stock[[i]]<- within(stock[[i]], {
              IJ1[y,] <- get_survey(F_full=0, M=0, N=J1N[y,], slxC[y,],
                                slxI=selI, timeI=0, qI=qI)
            }
```

This is happening because Rargom 4 (PR #171) added DecCatch and Tanom arguments to the ``get_survey()`` function
```
get_survey <- function(F_full, M, N, slxF, slxI, timeI, qI, DecCatch, Tanom, y){
```

Sleuthing around, it looks like looks like DecCatch is set in the stock parameters files. However it is missing from the pollock and yellowtailGB files.

I need a little help on how to set DecCatch and Tanom to be consistent with a standard fisheries model.

**Comment by mle2718** [comment]
Right now I have it set the same way as it is set in 
https://github.com/lkerr/groundfish-MSE/blob/master/functions/managementProc/get_indexData.R#L12-L14

<- get_survey(F_full=F_full[y], M=natM[y], N=J1N[y,], slxC[y,], 
                           slxI=selI, timeI=timeI, qI=qI, 
                         DecCatch=DecCatch, Tanom=Tanom[y],y=y)

But I'm not 100% sure this is correct.

**Comment by lkerr** [comment]
DecCatch: switch for if survey catchability decreases over time/temperature or not. If set to TRUE, survey catchability 
Tanom: temperature anomaly
 y: year in simulation 

This code was created to decrease/increase survey catchability as a function of temperature anomaly.  You will want to turn these options off.  You will want to set DecCatch=FALSE, Tanom=0,y=1

**Comment by mle2718** [comment]
Thanks!
