### ISSUE TITLE
yellowtailflounderGB with the mincatch option fails.

### ISSUE THREAD

**Issue by mle2718** [lkerr/groundfish-MSE#238]
There are two problems:
1.  /data/data_raw/AssessmentHistory/yellowtailflounderGB_Discard.csv is missing. 
2. The following code is missing the bit to read in the yellowtailflounderGB_Discard.csv.
https://github.com/lkerr/groundfish-MSE/blob/170517f04d2ae9fe75ee35beb6f79267fabd6430/functions/managementProc/get_nextF.R#L219-L246

@mle2718 is working on item 2.

**Comment by jerellejesse** [comment]
Yellowtail flounder historical data and US discards have been updated.
