### ISSUE TITLE
transboundary stocks

### ISSUE THREAD

**Issue by mle2718** [lkerr/groundfish-MSE#257]
How should I deal with stocks that them -- I only have the U.S. removals in my model.

**Comment by lkerr** [comment]
Hmmm...we can discuss next week. We can create an allocation model that codes in US/CAN allocations. There is information on the % across years. These are also based on distribution of species, but I don't think the percentage has changed that much over time.

**Comment by lkerr** [comment]
This presentation has information relevant to this issue: https://s3.us-east-1.amazonaws.com/nefmc.org/1a_TMGC_Presentation.pdf

**Comment by mle2718** [comment]
https://www.nefmc.org/calendar/sep-12-13-transboundary-management-guidance-committee-tmgc-meeting

**Comment by mle2718** [comment]
323c90a236215ecdbcdde2a017e18798b0d7b2a1

I've pulled the Canada Quotas and catches for the 3 transboundary stocks. I added the US and Canadian quota to get the total quota. And I've included canadian catch as another "non-sector, non-rec" fleet.   The data changes will carry over to the next model run. 

I should also update the catch and ACL data past 2017.
