### ISSUE TITLE
scaling of the "economic" survey and SSB

### ISSUE THREAD

**Issue by mle2718** [lkerr/groundfish-MSE#258]
I'm a little worried about the units and scaling of the economic survey. And possibly SSB.
There are two concerns
1. What are the units of the simulated economic survey?  Are they consistent across all stocks? See: https://github.com/lkerr/groundfish-MSE/issues/128

2. I use the simulated survey as a predictor in the economic model? How can we ensure they are close to accurate? 

See the attached
[diagnose_SSB_trawl.pdf](https://github.com/lkerr/groundfish-MSE/files/9648972/diagnose_SSB_trawl.pdf)

**Comment by lkerr** [comment]
We can double check on #1 (there are places where we convert between kg to mt) and can work on #2-we hadn't tried to tune the indices to be on the exact same scale as the actual trawl survey, but can likely do this by adjusting catchability.  By "close to accurate" do you mean on the same scale ? or following the same trend?

**Comment by mle2718** [comment]
@lkerr same scale. The trend should get picked up automatically --it follows the simulated SSB. 
I can't upload the .Rdata file -- I'll send them by email.
I tried writing the results to csvs, but then you have to wrestle it from back into an array of the proper dimensions.

**Comment by mle2718** [comment]
I'm addressed this by creating an trawl-to-econ multiplier. This just adjusts the EconSurvey so it matches actual trends. Mostly done here:

9b758785bb9eb9bc89bf71af87f9e4acc08d10c6 , but with these fixes
bcb3c70eb6348439f18f8ce3888e798804a2a8fc
f3e6136131098dc202b5a88a9c8a939e35b39c72

Even if the units are different, the multiplier should take care of that.  The trends match well enough, so I'm marking this as closed.
