### ISSUE TITLE
reading in

### ISSUE THREAD

**Issue by mle2718** [lkerr/groundfish-MSE#275]
There's something in the code that is reading in alot of data and printing it to the console. I think it's doing so yearly. 

the printing is making it a bit tricky for me to figure out how far along the economic simulations are. I'd like to squelch the printing of it, and I know how...but I haven't figured out where in the code to look.

Any idea what's doing this?

```
Read 1 item
Read 1 item
Read 1 item
Read 1 item
Read 1 item
Read 1 item
Read 333 items
Read 1 item
Read 1 item
Read 333 items
Read 1 item
Read 333 items
Read 1 item
Read 1 item
Read 1 item
Read 1 item
Read 1 item
Read 1 item
Read 37 items
Read 1 item
Read 60 items
Read 1 item
Read 1 item
Read 2 items
Read 1 item
Read 1 item
Read 1 item
Read 370 items
Read 370 items
Read 333 items
Read 1 item
Read 1 item
Read 1 item
Read 1 item
Read 1 item
Read 1 item
Read 1 item
Read 1 item
Read 1 item
Read 1 item
Read 60 items
Read 481 items
Read 1 item
...
Read 1 item
```

**Comment by jerellejesse** [comment]
Yes! That's the ASAP assessment reading in the .dat file. get_ASAP.R function in functions/assessment folder

**Comment by mle2718** [comment]
is it this line:
```
    dat_file <- ReadASAP3DatFile(paste('assessment/ASAP/', stockName, ".dat", sep = ''))
```

**Comment by jerellejesse** [comment]
That's awesome, thanks!
