### ISSUE TITLE
plotting code

### ISSUE THREAD

**Issue by mle2718** [lkerr/groundfish-MSE#276]
https://www.sciencedirect.com/science/article/pii/S0165783623000450

Can someone point me to the code used to make Figure 3 in the paper? I know it's somewhere in postprocessing/Plots, but I'm not really sure which one it is.

**Comment by jerellejesse** [comment]
Those should be the SSBplotwithCI, FplotwithCI, and CatchplotwithCI. But there must have been code that combines them in one plot, so I can do some digging or maybe @mdmazur knows off the top of her head.

**Comment by mle2718** [comment]
> But there must have been code that combines them in one plot, so I can do some digging or maybe @mdmazur knows off the top of her head.

Thanks @jerellejesse .. I don't need that now.  No need to go digging around for it.
