### ISSUE TITLE
updates to hydra input files during MSE loop

### ISSUE THREAD

**Issue by gavinfay** [lkerr/groundfish-MSE#280]
@emilylil It looks like `get_hydra()` is rewriting the `.dat`, `ts.dat`, and `.pin` files each time-step.
The `ts.dat` file does not need updating and can be left alone.

**Comment by gavinfay** [comment]
Ah, I suppose it depends on which tables are being used to get the new observations. Never mind!

**Comment by emilylil** [comment]
Normally I'd agree, but the way I have get_hydra() set up means I need to generate dummy data for the projection years so that hydra can assign "predicted" values to those columns. I can make this change but might have to fiddle with the tpl.

**Comment by emilylil** [comment]
Normally I'd agree, but the way I have get_hydra() set up means I need to generate dummy data for the projection years so that hydra can assign "predicted" values to those columns. I can make this change but might have to fiddle with the tpl.
